source 'https://github.com/CocoaPods/Specs.git'

target 'NNMultipleImagePickerController_Example', :exclusive => true do
  pod "NNMultipleImagePickerController", :path => "../"
end

target 'NNMultipleImagePickerController_Tests', :exclusive => true do
  pod "NNMultipleImagePickerController", :path => "../"

  
end
